- name: AS3-Playbook
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    uri_method: POST

  vars_files:
    - ../creds/creds.yaml

  tasks:

  - name: Create an AS3 deployment
    uri:
      url: https://3.9.95.177/mgmt/shared/appsvcs/declare
      user: "{{as3_user}}"
      password: "{{as3_pass}}"
      method: "{{uri_method}}"
      body: "{{ lookup('file','./as3-decl.json') }}"
      force_basic_auth: yes
      status_code: 200
      body_format: json
      validate_certs: no
